# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageLoading' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
        pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SDDownloadManager'
	pod 'SDWebImage'

  # Pods for ImageLoading

  target 'ImageLoadingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
